openapi: 3.0.0
info:
  title: Trial API World Clock
  description: |-
    # Introduction
    This is Trial API World Clock
  version: 1.0.0
servers:
  - url: https://<API Gateway domain>/<env>
paths:
  /academicapi/worldclock:
    get:
      tags:
        - academic-api
      summary: >-
        It is API to query date by inputing timezone
      description: Get date by timezone
      parameters:
        - name: timezone
          in: query
          schema:
            type: string
          example: Europe/London
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
